name: my_app_test

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner on your local Windows PC
    defaults:
      run:
        shell: cmd  # Use CMD shell for Windows commands

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output C:\Temp\PublishOutput

      # Stop the IIS website and app pool to release file locks
      - name: Stop IIS Website and App Pool
        run: |
          C:\Windows\System32\inetsrv\appcmd.exe stop site "TestApp"
          C:\Windows\System32\inetsrv\appcmd.exe stop apppool /apppool.name:"TestApp" || exit 0
        # Replace "TestAppPool" with your actual app pool name; || exit 0 ignores errors if it’s already stopped

      # Deploy the published files to IIS folder
      - name: Deploy to IIS
        run: xcopy C:\Temp\PublishOutput\* C:\inetpub\wwwroot\myapp /E /H /C /I /Y /D
        # Fixed path (removed "/E" after "myapp") and added /D for incremental updates

      # Start the IIS website and app pool
      - name: Start IIS Website and App Pool
        run: |
          C:\Windows\System32\inetsrv\appcmd.exe start site "TestApp"
          C:\Windows\System32\inetsrv\appcmd.exe start apppool /apppool.name:"TestApp" || exit 0
        # Replace "TestAppPool" with your actual app pool name

      # Clean up temporary publish folder
      - name: Clean up
        run: rmdir /S /Q C:\Temp\PublishOutput