name: my_app_test

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner on your local Windows PC
    defaults:
      run:
        shell: cmd  # Use CMD shell for Windows commands

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for consistency

      # Set up .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4  # Updated to v4
        with:
          dotnet-version: '8.0.x'  # Adjust to your .NET version if needed

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output C:\Temp\PublishOutput

      # Stop the IIS website
      - name: Stop IIS Website
        run: C:\Windows\System32\inetsrv\appcmd.exe stop site "TestApp"  # Full path to appcmd

      # Deploy the published files to IIS folder
      - name: Deploy to IIS
        run: xcopy C:\Temp\PublishOutput\* C:\inetpub\wwwroot\myapp/E /H /C /I /Y
        # Updated to "TestApp" to match the IIS site name

      # Start the IIS website
      - name: Start IIS Website
        run: C:\Windows\System32\inetsrv\appcmd.exe start site "TestApp"  # Full path to appcmd

      # Optional: Clean up temporary publish folder
      - name: Clean up
        run: rmdir /S /Q C:\Temp\PublishOutput